### ISSUE TITLE
  expanded_attn_mask = causal_4d_mask.masked_fill(expanded_attn_mask.bool(), torch.finfo(dtype).min) RuntimeError: The size of tensor a (3509) must match the size of tensor b (7017) at non-singleton dimension 3

### ISSUE THREAD

**Issue by seeyourcell** [FasterDecoding/SnapKV#13]
I use transformers==4.27.0 ，why has this error？

RuntimeError: The size of tensor a (3509) must match the size of tensor b (7017) at non-singleton dimension 3

**Comment by seeyourcell** [comment]
expanded_attn_mask = causal_4d_mask.masked_fill(expanded_attn_mask.bool(), torch.finfo(dtype).min)
RuntimeError: The size of tensor a (3509) must match the size of tensor b (7017) at non-singleton dimension 3

**Comment by pengshuang** [comment]
Hello, I met the same problem, how do you solve it?

**Comment by Zhutianyi7230** [comment]
I meet the same question when I set `use_flasg_attention_2=False`
