### ISSUE TITLE
What prompt was used in Needle in  a Haystack test?

### ISSUE THREAD

**Issue by 66RING** [FasterDecoding/SnapKV#14]
I try to reproduce needle test with LWM-Text-Chat-1M but the model just refuse to answer. I have tried following prompts in Needle test and the model just generate `</s>`

```
<s>[INST] <<SYS>>
You are a helpful AI bot that answers questions for a user. Keep your response short and direct
<</SYS>>
{ context }

{retrieval_question} Don't give information outside the document or repeat your findings
[/INST]
```

and 

```
<s>[INST] <<SYS>>
You are a helpful AI bot that answers questions for a user. Keep your response short and direct
<</SYS>>
{ context }

{retrieval_question} Don't give information outside the document or repeat your findings
[/INST]</s>
```

**Comment by WendyH1108** [comment]
We used the same evaluation code as https://github.com/FranxYao/Long-Context-Data-Engineering/blob/main/eval/needle/needle_in_haystack.py


return [
                {
                    "role": "system",
                    "content": "You are a helpful AI bot that answers questions for a user. Keep your response short and direct"
                },
                {
                    "role": "user",
                    "content": context
                    },
                {
                    "role": "user",
                    "content": f"{self.retrieval_question} Don't give information outside the document or repeat your findings. The document definitely contains the answer, and I'm 100% sure. So try your best to find it."
                },
                {
                    "role": "assistant",
                    "content":"",
                },

**Comment by YUECHE77** [comment]
> I try to reproduce needle test with LWM-Text-Chat-1M but the model just refuse to answer. I have tried following prompts in Needle test and the model just generate `</s>`
> 
> ```
> <s>[INST] <<SYS>>
> You are a helpful AI bot that answers questions for a user. Keep your response short and direct
> <</SYS>>
> { context }
> 
> {retrieval_question} Don't give information outside the document or repeat your findings
> [/INST]
> ```
> 
> and
> 
> ```
> <s>[INST] <<SYS>>
> You are a helpful AI bot that answers questions for a user. Keep your response short and direct
> <</SYS>>
> { context }
> 
> {retrieval_question} Don't give information outside the document or repeat your findings
> [/INST]</s>
> ```

Hi, could you share your prompt that you eventually used?

I think the following template is for testing on OpenAI models, and we should not use it:

return [
{
"role": "system",
"content": "You are a helpful AI bot that answers questions for a user. Keep your response short and direct"
},
{
"role": "user",
"content": context
},
{
"role": "user",
"content": f"{self.retrieval_question} Don't give information outside the document or repeat your findings. The document definitely contains the answer, and I'm 100% sure. So try your best to find it."
},
{
"role": "assistant",
"content":"",
},

According to the code in "https://github.com/FranxYao/Long-Context-Data-Engineering/blob/main/eval/needle/needle_in_haystack.py", they are using: 

f"<|im_start|> This is a very long story book: <book> {context} </book>.\n Based on the content of the book, Question: {self.retrieval_question}\nAnswer:" 

Could you tell me is that the one you tested on?

Thank you so much!
